class AdvertisementNotFoundError(Exception):
    ...

class UserNotFoundError(Exception):
    ...

class AdvertisementCreationError(Exception):
    ...

class UserNotCreationError(Exception):
    ...

class ModerationResultNotFoundError(Exception):
    ...

class ModerationResultCreationError(Exception):
    ...

class AccountNotFoundError(Exception):
    ...

class AccountCreationError(Exception):
    ...

class AccountBlockedError(Exception):
    ...

class UnauthorizedError(Exception):
    ...

class AuthorizedError(Exception):
    ...