class AdvertisementNotFoundError(Exception):
    ...

class UserNotFoundError(Exception):
    ...

class AdvertisementCreationError(Exception):
    ...

class UserNotCreationError(Exception):
    ...

class ModerationResultNotFoundError(Exception):
    ...

class ModerationResultCreationError(Exception):
    ...